import Head from 'next/head';
import { Button, InfoBadge, ProductCard, SpecialCard } from '../components/';
import { WithLayout } from '../Layout';
import { useAppSelector } from '../store/hooks';
import { AppState, wrapper } from '../store/store';

function Home(): JSX.Element {
  const catalog = useAppSelector((state: AppState) => state.catalog);
  console.log(catalog);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello!
      <Button>Primary</Button>
      <Button styleType='ghost'>Ghost</Button>
      <Button styleType='plain'>Plain</Button>
      <Button disabled>Plain</Button>
      <Button as='a' styleType='plain'>Plain</Button>
      <br></br>
      <InfoBadge size='s' styleType='accent'>Sale</InfoBadge>
      <InfoBadge size='l' styleType='gray'>Delivery</InfoBadge>
      <InfoBadge>Ingormation</InfoBadge>

      <ProductCard
        img='a5b88f36-e4cb-46bf-9ab1-da5789fa00aa.jpg'
        name='Jan Marini Age Intervention Duality'
        nameRus='Крем против морщин и акне с 0,5% ретинола'
        price={7500}
        oldPrice={8400}
      />

      <Button like='Link' href='/catalog' styleType='plain'>Catalog</Button>
      {/* 
      <SpecialCard
        img='b5e99982-04d8-437f-ad7e-20bb28ce99ec.jpg'
        name='Jan Marini Age Intervention Duality'
        nameRus='Крем против морщин и акне с 0,5% ретинола'
        price={7500}
        type='long'
      />

      <SpecialCard
        img='b5e99982-04d8-437f-ad7e-20bb28ce99ec.jpg'
        name='Jan Marini Age Intervention Duality'
        nameRus='Крем против морщин и акне с 0,5% ретинола'
        price={7500}
        type='square'
      /> */}
    </div>
  );
}

export const getStaticProps = wrapper.getStaticProps(store => () => {

});

export default WithLayout(Home);
